version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_development
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    networks:
      - nuxpi_network
    ports:
      - '5432:5432' # Exporta el puerto de PostgreSQL

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./volumes/redis_data:/data
    networks:
      - nuxpi_network
    ports:
      - '6379:6379' # Exporta el puerto de Redis

volumes:
  postgres_data:
  redis_data:

networks:
  nuxpi_network:
    driver: bridge
